import {
  mdiAirplane,
  mdiAlarmLight,
  mdiAlert,
  mdiAlertCircle,
  mdiBalloon,
  mdiBat,
  mdiBed,
  mdiBell,
  mdiBellRing,
  mdiBird,
  mdiBomb,
  mdiBug,
  mdiBullhorn,
  mdiCakeVariant,
  mdiCalendar,
  mdiCalendarBlank,
  mdiCalendarStar,
  mdiCampfire,
  mdiCandycane,
  mdiCar,
  mdiCat,
  mdiCheckCircle,
  mdiClockOutline,
  mdiCoffee,
  mdiCow,
  mdiDog,
  mdiDoorClosed,
  mdiDoorOpen,
  mdiDoorbell,
  mdiDuck,
  mdiEggEaster,
  mdiEmoticonHappy,
  mdiFire,
  mdiFirework,
  mdiFish,
  mdiFlower,
  mdiGamepadVariant,
  mdiGarage,
  mdiGhost,
  mdiGift,
  mdiHalloween,
  mdiGuitarElectric,
  mdiHeadphones,
  mdiHeart,
  mdiHome,
  mdiHorse,
  mdiInformation,
  mdiKey,
  mdiLeaf,
  mdiLightningBolt,
  mdiLock,
  mdiMessage,
  mdiMicrophone,
  mdiMovie,
  mdiMusic,
  mdiMusicBoxMultiple,
  mdiMusicNote,
  mdiOwl,
  mdiPartyPopper,
  mdiPaw,
  mdiPhone,
  mdiPiano,
  mdiPineTree,
  mdiPizza,
  mdiPumpkin,
  mdiRobot,
  mdiRocketLaunch,
  mdiSkull,
  mdiSnowflake,
  mdiSofa,
  mdiSpeaker,
  mdiSpeakerWireless,
  mdiSpider,
  mdiStar,
  mdiSword,
  mdiTelevision,
  mdiThumbUp,
  mdiTimer,
  mdiTrain,
  mdiTrophy,
  mdiUfo,
  mdiUmbrella,
  mdiVolumeHigh,
  mdiWashingMachine,
  mdiWater,
  mdiWeatherNight,
  mdiWeatherSnowy,
  mdiWhiteBalanceSunny,
  mdiWindowOpen,
} from "@mdi/js";

// Curated subset of Material Design Icons: the names the API stores
// (`"mdi:door-open"`) map to SVG paths bundled with the app. Anything outside
// this set renders as a generic music note, so a typo or a custom Home
// Assistant icon never leaves a hole in the UI. The Organize IconPicker offers
// exactly these names. Every icon the backend seeds or defaults to must be listed
// here (see the "backend defaults" spec): calendar-blank (built-in regular season),
// calendar-star (new-season default) and music-note (seeded general category).
const ICONS: Record<string, string> = {
  "music-note": mdiMusicNote,
  "music": mdiMusic,
  "music-box-multiple": mdiMusicBoxMultiple,
  "volume-high": mdiVolumeHigh,
  "speaker": mdiSpeaker,
  "speaker-wireless": mdiSpeakerWireless,
  "bell": mdiBell,
  "bell-ring": mdiBellRing,
  "bullhorn": mdiBullhorn,
  "microphone": mdiMicrophone,
  "headphones": mdiHeadphones,
  "guitar-electric": mdiGuitarElectric,
  "piano": mdiPiano,
  "alarm-light": mdiAlarmLight,
  "alert": mdiAlert,
  "alert-circle": mdiAlertCircle,
  "information": mdiInformation,
  "check-circle": mdiCheckCircle,
  "lightning-bolt": mdiLightningBolt,
  "door-open": mdiDoorOpen,
  "door-closed": mdiDoorClosed,
  "doorbell": mdiDoorbell,
  "home": mdiHome,
  "garage": mdiGarage,
  "lock": mdiLock,
  "key": mdiKey,
  "bed": mdiBed,
  "sofa": mdiSofa,
  "window-open": mdiWindowOpen,
  "dog": mdiDog,
  "cat": mdiCat,
  "bird": mdiBird,
  "paw": mdiPaw,
  "horse": mdiHorse,
  "cow": mdiCow,
  "fish": mdiFish,
  "duck": mdiDuck,
  "owl": mdiOwl,
  "bug": mdiBug,
  "party-popper": mdiPartyPopper,
  "cake-variant": mdiCakeVariant,
  "balloon": mdiBalloon,
  "gift": mdiGift,
  "halloween": mdiHalloween,
  "pine-tree": mdiPineTree,
  "snowflake": mdiSnowflake,
  "ghost": mdiGhost,
  "pumpkin": mdiPumpkin,
  "heart": mdiHeart,
  "firework": mdiFirework,
  "candycane": mdiCandycane,
  "flower": mdiFlower,
  "leaf": mdiLeaf,
  "white-balance-sunny": mdiWhiteBalanceSunny,
  "weather-night": mdiWeatherNight,
  "egg-easter": mdiEggEaster,
  "star": mdiStar,
  "calendar": mdiCalendar,
  "calendar-blank": mdiCalendarBlank,
  "calendar-star": mdiCalendarStar,
  "bat": mdiBat,
  "spider": mdiSpider,
  "campfire": mdiCampfire,
  "umbrella": mdiUmbrella,
  "weather-snowy": mdiWeatherSnowy,
  "trophy": mdiTrophy,
  "car": mdiCar,
  "clock-outline": mdiClockOutline,
  "timer": mdiTimer,
  "phone": mdiPhone,
  "message": mdiMessage,
  "thumb-up": mdiThumbUp,
  "emoticon-happy": mdiEmoticonHappy,
  "water": mdiWater,
  "fire": mdiFire,
  "robot": mdiRobot,
  "rocket-launch": mdiRocketLaunch,
  "gamepad-variant": mdiGamepadVariant,
  "movie": mdiMovie,
  "television": mdiTelevision,
  "washing-machine": mdiWashingMachine,
  "bomb": mdiBomb,
  "skull": mdiSkull,
  "ufo": mdiUfo,
  "sword": mdiSword,
  "train": mdiTrain,
  "airplane": mdiAirplane,
  "coffee": mdiCoffee,
  "pizza": mdiPizza,
};

/** Icon used whenever a name is missing or unknown. */
export const FALLBACK_ICON = mdiMusicNote;

/** Every selectable icon as an API name (`mdi:...`), in display order. */
export const ICON_NAMES: string[] = Object.keys(ICONS).map((name) => `mdi:${name}`);

/** SVG path for an API icon name, or null when the name is not in the curated set. */
export function mdiPathFor(name: string): string | null {
  const key = name.trim().toLowerCase();
  const bare = key.startsWith("mdi:") ? key.slice(4) : key.includes(":") ? "" : key;
  return Object.hasOwn(ICONS, bare) ? (ICONS[bare] as string) : null;
}

/** Like {@link mdiPathFor}, but never null: unknown names yield the generic music note. */
export function resolveIcon(name: string | null | undefined): string {
  return (name ? mdiPathFor(name) : null) ?? FALLBACK_ICON;
}
