import {
  mdiBaby,
  mdiBalloon,
  mdiBat,
  mdiCakeVariant,
  mdiCalendar,
  mdiCalendarBlank,
  mdiCalendarStar,
  mdiCamera,
  mdiCampfire,
  mdiCandycane,
  mdiCastle,
  mdiCat,
  mdiCctv,
  mdiClockOutline,
  mdiCreation,
  mdiDog,
  mdiEggEaster,
  mdiEmoticonHappy,
  mdiFilm,
  mdiFilmstrip,
  mdiFilmstripBox,
  mdiFire,
  mdiFirework,
  mdiFlower,
  mdiGhost,
  mdiGift,
  mdiHalloween,
  mdiHeart,
  mdiHome,
  mdiLamp,
  mdiLeaf,
  mdiLightningBolt,
  mdiMovie,
  mdiMovieOpen,
  mdiMovieOpenPlay,
  mdiMusic,
  mdiPartyPopper,
  mdiPaw,
  mdiPineTree,
  mdiPirate,
  mdiPopcorn,
  mdiProjector,
  mdiProjectorScreen,
  mdiPumpkin,
  mdiRobot,
  mdiRocketLaunch,
  mdiShimmer,
  mdiSkull,
  mdiSnowflake,
  mdiSofa,
  mdiSpider,
  mdiStar,
  mdiSunglasses,
  mdiSword,
  mdiTelevision,
  mdiTheater,
  mdiTicket,
  mdiTicketConfirmation,
  mdiTrophy,
  mdiUfo,
  mdiUmbrella,
  mdiVideo,
  mdiWeatherNight,
  mdiWeatherSnowy,
  mdiWhiteBalanceSunny,
} from "@mdi/js";

// Curated subset of Material Design Icons for a cinema library: the names the API stores
// (`"mdi:movie-open"`) map to SVG paths bundled with the app. Anything outside this set
// renders as the generic open-movie icon, so a typo or a custom Home Assistant icon never
// leaves a hole in the UI. The Organize IconPicker offers exactly these names. Every icon the
// backend seeds or defaults to must be listed here (see the "backend defaults" spec):
// movie-open (seeded Regular collection), calendar-blank (built-in regular season) and
// calendar-star (new-season default).
const ICONS: Record<string, string> = {
  "movie-open": mdiMovieOpen,
  "movie-open-play": mdiMovieOpenPlay,
  "movie": mdiMovie,
  "filmstrip": mdiFilmstrip,
  "filmstrip-box": mdiFilmstripBox,
  "film": mdiFilm,
  "video": mdiVideo,
  "projector": mdiProjector,
  "projector-screen": mdiProjectorScreen,
  "popcorn": mdiPopcorn,
  "ticket": mdiTicket,
  "ticket-confirmation": mdiTicketConfirmation,
  "television": mdiTelevision,
  "theater": mdiTheater,
  "camera": mdiCamera,
  "cctv": mdiCctv,
  "sunglasses": mdiSunglasses,
  "party-popper": mdiPartyPopper,
  "cake-variant": mdiCakeVariant,
  "balloon": mdiBalloon,
  "gift": mdiGift,
  "halloween": mdiHalloween,
  "pumpkin": mdiPumpkin,
  "candycane": mdiCandycane,
  "pine-tree": mdiPineTree,
  "snowflake": mdiSnowflake,
  "weather-snowy": mdiWeatherSnowy,
  "ghost": mdiGhost,
  "skull": mdiSkull,
  "bat": mdiBat,
  "spider": mdiSpider,
  "firework": mdiFirework,
  "heart": mdiHeart,
  "star": mdiStar,
  "egg-easter": mdiEggEaster,
  "flower": mdiFlower,
  "leaf": mdiLeaf,
  "white-balance-sunny": mdiWhiteBalanceSunny,
  "weather-night": mdiWeatherNight,
  "campfire": mdiCampfire,
  "umbrella": mdiUmbrella,
  "music": mdiMusic,
  "calendar": mdiCalendar,
  "calendar-blank": mdiCalendarBlank,
  "calendar-star": mdiCalendarStar,
  "clock-outline": mdiClockOutline,
  "sofa": mdiSofa,
  "home": mdiHome,
  "lamp": mdiLamp,
  "rocket-launch": mdiRocketLaunch,
  "ufo": mdiUfo,
  "robot": mdiRobot,
  "sword": mdiSword,
  "castle": mdiCastle,
  "pirate": mdiPirate,
  "shimmer": mdiShimmer,
  "creation": mdiCreation,
  "trophy": mdiTrophy,
  "fire": mdiFire,
  "lightning-bolt": mdiLightningBolt,
  "dog": mdiDog,
  "cat": mdiCat,
  "paw": mdiPaw,
  "baby": mdiBaby,
  "emoticon-happy": mdiEmoticonHappy,
};

/** Icon used whenever a name is missing or unknown. */
export const FALLBACK_ICON = mdiMovieOpen;

/** Every selectable icon as an API name (`mdi:...`), in display order. */
export const ICON_NAMES: string[] = Object.keys(ICONS).map((name) => `mdi:${name}`);

/** SVG path for an API icon name, or null when the name is not in the curated set. */
export function mdiPathFor(name: string): string | null {
  const key = name.trim().toLowerCase();
  const bare = key.startsWith("mdi:") ? key.slice(4) : key.includes(":") ? "" : key;
  return Object.hasOwn(ICONS, bare) ? (ICONS[bare] as string) : null;
}

/** Like {@link mdiPathFor}, but never null: unknown names yield the generic open-movie icon. */
export function resolveIcon(name: string | null | undefined): string {
  return (name ? mdiPathFor(name) : null) ?? FALLBACK_ICON;
}
